import type { Resource } from '@/types'

export const mockResources: Resource[] = [
  {
    _id: '1',
    title: 'Refactoring UI',
    slug: { current: 'refactoring-ui' },
    category: 'design',
    tags: ['Product Design', 'Wathan & Schoger', 'book'],
    summary: "The fastest way to make a designer's eye sharper. Tactical, opinionated, and impossible to unsee once read.",
    coverImageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=640&h=480&fit=crop',
    externalUrl: 'https://refactoringui.com',
    publishedAt: '2025-01-10',
    featured: true,
  },
  {
    _id: '2',
    title: 'Refactoring UI',
    slug: { current: 'refactoring-ui-2' },
    category: 'design',
    tags: ['Product Design', 'Wathan & Schoger', 'book'],
    summary: "The fastest way to make a designer's eye sharper. Tactical, opinionated, and impossible to unsee once read.",
    coverImageUrl: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=640&h=480&fit=crop',
    externalUrl: 'https://refactoringui.com',
    publishedAt: '2025-01-08',
    featured: false,
  },
  {
    _id: '3',
    title: 'Refactoring UI',
    slug: { current: 'refactoring-ui-3' },
    category: 'design',
    tags: ['Product Design', 'Wathan & Schoger', 'book'],
    summary: "The fastest way to make a designer's eye sharper. Tactical, opinionated, and impossible to unsee once read.",
    coverImageUrl: 'https://images.unsplash.com/photo-1557682260-96773eb01377?w=640&h=480&fit=crop',
    externalUrl: 'https://refactoringui.com',
    publishedAt: '2025-01-06',
    featured: false,
  },
  {
    _id: '4',
    title: 'Refactoring UI',
    slug: { current: 'refactoring-ui-4' },
    category: 'design',
    tags: ['Product Design', 'Wathan & Schoger', 'book'],
    summary: "The fastest way to make a designer's eye sharper. Tactical, opinionated, and impossible to unsee once read.",
    coverImageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=640&h=480&fit=crop',
    externalUrl: 'https://refactoringui.com',
    publishedAt: '2025-01-04',
    featured: false,
  },
  {
    _id: '5',
    title: 'Refactoring UI',
    slug: { current: 'refactoring-ui-5' },
    category: 'design',
    tags: ['Product Design', 'Wathan & Schoger', 'book'],
    summary: "The fastest way to make a designer's eye sharper. Tactical, opinionated, and impossible to unsee once read.",
    coverImageUrl: 'https://images.unsplash.com/photo-1567360425671-bc48de5e5c52?w=640&h=480&fit=crop',
    externalUrl: 'https://refactoringui.com',
    publishedAt: '2025-01-02',
    featured: false,
  },
  {
    _id: '6',
    title: 'Refactoring UI',
    slug: { current: 'refactoring-ui-6' },
    category: 'design',
    tags: ['Product Design', 'Wathan & Schoger', 'book'],
    summary: "The fastest way to make a designer's eye sharper. Tactical, opinionated, and impossible to unsee once read.",
    coverImageUrl: 'https://images.unsplash.com/photo-1557682250-33bd709cbe85?w=640&h=480&fit=crop',
    externalUrl: 'https://refactoringui.com',
    publishedAt: '2024-12-30',
    featured: false,
  },
  {
    _id: '7',
    title: 'Refactoring UI',
    slug: { current: 'refactoring-ui-7' },
    category: 'design',
    tags: ['Product Design', 'Wathan & Schoger', 'book'],
    summary: "The fastest way to make a designer's eye sharper. Tactical, opinionated, and impossible to unsee once read.",
    coverImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=640&h=480&fit=crop',
    externalUrl: 'https://refactoringui.com',
    publishedAt: '2024-12-20',
    featured: false,
  },
  {
    _id: '8',
    title: 'Refactoring UI',
    slug: { current: 'refactoring-ui-8' },
    category: 'design',
    tags: ['Product Design', 'Wathan & Schoger', 'book'],
    summary: "The fastest way to make a designer's eye sharper. Tactical, opinionated, and impossible to unsee once read.",
    coverImageUrl: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=640&h=480&fit=crop',
    externalUrl: 'https://refactoringui.com',
    publishedAt: '2024-12-15',
    featured: false,
  },
  {
    _id: '9',
    title: 'Refactoring UI',
    slug: { current: 'refactoring-ui-9' },
    category: 'design',
    tags: ['Product Design', 'Wathan & Schoger', 'book'],
    summary: "The fastest way to make a designer's eye sharper. Tactical, opinionated, and impossible to unsee once read.",
    coverImageUrl: 'https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?w=640&h=480&fit=crop',
    externalUrl: 'https://refactoringui.com',
    publishedAt: '2024-12-10',
    featured: false,
  },
  {
    _id: '10',
    title: 'Refactoring UI',
    slug: { current: 'refactoring-ui-10' },
    category: 'design',
    tags: ['Product Design', 'Wathan & Schoger', 'book'],
    summary: "The fastest way to make a designer's eye sharper. Tactical, opinionated, and impossible to unsee once read.",
    coverImageUrl: 'https://images.unsplash.com/photo-1549490349-8643362247b5?w=640&h=480&fit=crop',
    externalUrl: 'https://refactoringui.com',
    publishedAt: '2024-12-05',
    featured: false,
  },
  {
    _id: '11',
    title: 'Refactoring UI',
    slug: { current: 'refactoring-ui-11' },
    category: 'design',
    tags: ['Product Design', 'Wathan & Schoger', 'book'],
    summary: "The fastest way to make a designer's eye sharper. Tactical, opinionated, and impossible to unsee once read.",
    coverImageUrl: 'https://images.unsplash.com/photo-1579547945413-497e1b99dac0?w=640&h=480&fit=crop',
    externalUrl: 'https://refactoringui.com',
    publishedAt: '2024-11-30',
    featured: false,
  },
  {
    _id: '12',
    title: 'Refactoring UI',
    slug: { current: 'refactoring-ui-12' },
    category: 'design',
    tags: ['Product Design', 'Wathan & Schoger', 'book'],
    summary: "The fastest way to make a designer's eye sharper. Tactical, opinionated, and impossible to unsee once read.",
    coverImageUrl: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=640&h=480&fit=crop',
    externalUrl: 'https://refactoringui.com',
    publishedAt: '2024-11-25',
    featured: false,
  },
]
